steps:
  # Build and deploy article-to-speech
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd article-to-speech
        gcloud builds submit --config cloudbuild.yaml .

  # Build and deploy lyria-journal
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd music/lyria-journal
        gcloud builds submit --config cloudbuild.yaml .

  # Build and deploy lyria-journal-nodejs
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd music/lyria-journal-nodejs
        gcloud builds submit --config cloudbuild.yaml .

  # Build and deploy lyria-journal-react
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd music/lyria-journal-react
        gcloud builds submit --config cloudbuild.yaml .

  # Build and deploy lyria-journal-go
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd music/lyria-journal-go
        gcloud builds submit --config cloudbuild.yaml .
